Just use one job and work with json objects instead of Github objects

diff --git a/.github/workflows/package-tests.yml b/.github/workflows/package-tests.yml
--- a/.github/workflows/package-tests.yml
+++ b/.github/workflows/package-tests.yml
@@ -7,7 +7,7 @@ on:
 
 jobs:
   matrix:
-    name: Find modified packages
+    name: Test package
     runs-on: Ubuntu-20.04
     steps:
       - name: Checkout code
@@ -20,44 +20,76 @@ jobs:
         id: find-packages
         run: echo "::set-output name=packages::$(php .github/get-modified-packages.php $(find src/Symfony -mindepth 2 -type f -name composer.json -printf '%h\n' | jq -R -s -c 'split("\n")[:-1]') $(git diff --name-only origin/${{ github.base_ref }} HEAD | grep src/ | jq -R -s -c 'split("\n")[:-1]'))"
 
-    outputs:
-      # Make the outputs accessible outside this job
-      packages: ${{ steps.find-packages.outputs.packages }}
-
-  meta-files:
-    needs: matrix
-    name: Meta files
-    runs-on: Ubuntu-20.04
-    strategy:
-      fail-fast: false
-      matrix:
-        package: ${{ fromJson(needs.matrix.outputs.packages) }}
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
       - name: Verify meta files exists
         run: |
-          test -f ${{ matrix.package.directory }}/.gitattributes
-          test -f ${{ matrix.package.directory }}/.gitignore
-          test -f ${{ matrix.package.directory }}/CHANGELOG.md
-          test -f ${{ matrix.package.directory }}/LICENSE
-          test -f ${{ matrix.package.directory }}/phpunit.xml.dist
-          test ! -f ${{ matrix.package.directory }}/phpunit.xml
-          test -f ${{ matrix.package.directory }}/README.md
+          ok=0
+          #set -xv;
+          _file_exist() {
+            if [ ! -f "${1}" ]; then
+              echo "File ${1} does not exist"
+              return 1
+            fi
+          }
 
-      - name: License file is correct
-        if: ${{ matrix.package.new }}
-        run: |
-          FIRST_LINE="Copyright (c) $(date +"%Y") Fabien Potencier"
-          PACKAGE_FIRST_LINE=$(head -1 ${{ matrix.package.directory }}/LICENSE)
-          [[ "$FIRST_LINE" == "$PACKAGE_FIRST_LINE" ]]
+          _file_not_exist() {
+            if [ -f "${1}" ]; then
+              echo "File ${1} should not be here"
+              return 1
+            fi
+          }
 
-          TEMPLATE=$(tail -n +2 LICENSE)
-          PACKAGE_LICENSE=$(tail -n +2 ${{ matrix.package.directory }}/LICENSE)
-          [[ "$TEMPLATE" == "$PACKAGE_LICENSE" ]]
+          _correct_license_file() {
+            FIRST_LINE="Copyright (c) $(date +"%Y") Fabien Potencier"
+            PACKAGE_FIRST_LINE=$(head -1 ${1})
+            if [[ "$FIRST_LINE" != "$PACKAGE_FIRST_LINE" ]]; then
+              echo "First line of the license file is wrong. Maybe it is the wrong year?"
+              return 1
+            fi
 
-      - name: Package is in composer.json's replace
-        if: ${{ matrix.package.new && !matrix.package.component_bridge }}
-        run: cat composer.json | jq -e '.replace."${{ matrix.package.name }}"|test("self.version")'
+            TEMPLATE=$(tail -n +2 LICENSE)
+            PACKAGE_LICENSE=$(tail -n +2 ${1})
+            if [[ "$TEMPLATE" != "$PACKAGE_LICENSE" ]]; then
+              echo "Wrong content in license file"
+              return 1
+            fi
+          }
+
+          json='${{ steps.find-packages.outputs.packages }}'
+          for package in $(echo "${json}" | jq -r '.[] | @base64'); do
+              _jq() {
+                echo ${package} | base64 --decode | jq -r ${1}
+              }
+
+              DIR=$(_jq '.directory')
+              NAME=$(_jq '.name')
+              echo "::group::$NAME"
+              localExit=0
+
+              _file_exist $DIR/.gitattributes || localExit=1
+              _file_exist $DIR/.gitignore || localExit=1
+              _file_exist $DIR/CHANGELOG.md || localExit=1
+              _file_exist $DIR/LICENSE || localExit=1
+              _file_exist $DIR/phpunit.xml.dist || localExit=1
+              _file_exist $DIR/README.md || localExit=1
+              _file_not_exist $DIR/phpunit.xml || localExit=1
+
+              if [ $(_jq '.new') == true ]; then
+                echo "Verifying new package"
+                _correct_license_file $DIR/LICENSE || localExit=1
+
+                if [ $(_jq '.component_bridge') == false ]; then
+                  if [ ! $(cat composer.json | jq -e ".replace.\"$NAME\"|test(\"self.version\")") ]; then
+                    echo "Composer.json's replace section need to contain $NAME"
+                    localExit=1
+                  fi
+                fi
+              fi
+
+              ok=$(( $localExit || $ok ))
+              echo ::endgroup::
+              if [ $localExit -ne 0 ]; then
+                echo "::error::$NAME failed"
+              fi
+          done
+
+          exit $ok
